big nbdroot fixup

diff --git a/scripts/fll b/scripts/fll
--- a/scripts/fll
+++ b/scripts/fll
@@ -87,6 +87,13 @@ fll_finger_blockdevs()
 				# avoid disk type checking
 				#
 				;;
+			nbd*)
+				#
+				# udev doesn't reflect state of nbd device
+				#
+				[ -n "${FLL_NBD}" ] || continue
+				nbd-client -c ${disk} > /dev/null || continue
+				;;
 			*)
 				udevadm info -q env -p "${path}" | \
 					grep -q 'ID_TYPE=disk' || continue
@@ -96,7 +103,8 @@ fll_finger_blockdevs()
 		#
 		# use shell wildcard to expand partitions from sysfs hier
 		#
-		for sub_path in ${path}/${disk}[1-9]*; do
+		for sub_path in ${path}/${disk}[1-9]* ${path}/${disk}p[1-9]*; do
+			# trying p between disk and partition number for nbd
 			[ -e "${sub_path}" ] || continue
 
 			part="${sub_path#${path}/}"
@@ -461,6 +469,24 @@ mountroot()
 	#
 	for opt in $(cat /proc/cmdline); do
 		case "${opt}" in
+			BOOTIF=*)
+				# #577149
+				# initramfs init exports it blank
+				#   and reverses it
+				if [ -z "${BOOTIF}" ]; then
+					BOOTIF="${opt#BOOTIF=}"
+					# initramfs is parsing backwards 
+					temp_mac=${BOOTIF#*-}
+					BOOTIF=""
+					IFS='-'
+					for x in $temp_mac; do
+						BOOTIF="-${x}${BOOTIF}"
+					done
+					unset IFS
+					BOOTIF="01${BOOTIF}"
+					export BOOTIF
+				fi
+				;;
 			firmware)
 				FLL_FIRMWARE="yes"
 				;;
@@ -494,6 +520,18 @@ mountroot()
 				FLL_IMAGE_FILE="${opt#image_name=}"
 				FLL_IMAGE_LOCATION="${FLL_IMAGE_DIR}/${FLL_IMAGE_FILE}"
 				;;
+			nbdroot=*)
+				# triggers finger_blockdevs
+				# if fromhd device not set and not using dhcp then
+				#    static may not work in nbd-client and
+				#    no device to use to re-run nbd-client safely
+				FLL_FROMHD="yes"
+				# need to know to
+				#   tell finger_blockdevs to check nbd*
+				#   call configure_networking
+				#     nbdroot probably should always call it
+				FLL_NBD="${opt#nbdroot=}"
+				;;
 			persist*)
 				FLL_PERSIST="yes"
 				FLL_PERSIST_FILE="${FLL_DISTRO_NAME}-rw"
@@ -520,6 +558,103 @@ mountroot()
 				;;
 		esac
 	done
+
+	#
+	# Prepare for nbd
+	#
+	if [ -n "$FLL_NBD" ] ; then
+		# A range of issues need "fixing" for nbd
+		#   nbd will only run configure_networking (c_n) if nbdroot=dhcp,
+		#     running c_n here before local-top is therefore vital for now
+		#     I strongly suspect nbd will "fix" the requirement on this
+		#   DEVICE is hardcoded to eth0 if c_n is run here (not exported to nbd)
+		#   ROOTPATH won't be available to nbd if c_n succeeds here
+		#   nbd won't have a DEVICE unless set by ip= or BOOTIF
+		[ "$quiet" != "y" ] && log_begin_msg "Preparing for nbd"
+		# BOOTIF will supply the DEVICE if set
+		if [ -z "${BOOTIF}" ]; then
+			# #566295 means c_n demands a device unless IP is not one of
+			# ""|on|any|dhcp|both|off|none|bootp|rarp
+			# Need to concern ourselves with making sure we can both:
+			#   give good args to c_n when run here
+			#   export good args for scripts (e.g. nbd) to match afterwards
+
+			# blank DEVICE (was eth0 from initramfs.conf)
+			# this change is coming in initramfs-tools anyway
+			DEVICE=""
+
+			# convert ip into a full spec for shortcut cases
+			# full specs don't use DEVICE in c_n except to test file
+			case ${IP} in
+				""|on|any|dhcp|both|off|none)
+					# stops c_n having no device
+					# we want any device and can't guess
+					# we can't use all as that breaks parsing
+					# we will run ipconfig excessively, but it's ok
+					IP="::::::"
+					;;
+				bootp|rarp)
+					# stops c_n having no device
+					# we want any device and can't guess
+					IP="::::::${IP}"
+					;;
+				*:*)
+					# this is a full(ish) ipconfig spec
+					# ipconfig will fill remaining defaults itself
+					# if it can parse DEVICE it will exit first c_n nicely
+					# if it can't parse DEVICE we can only wait for c_n
+					;;
+				*)
+					# cosmetic fix but matches ipconfig, fits c_n
+					# makes explicit short device form
+					# DEVICE lets ROUNDTT loop exit
+					DEVICE="${IP}"
+					;;
+			esac
+		fi
+
+		# configure_networking might get run again (e.g. by nbdroot)
+		# c_n can be run multiple times safely on DEVICE/BOOTIF
+		# it won't reparse the /tmp/net-*.conf file though!
+		# exporting DEVICE now means future c_n from scripts won't rerun ipconfig
+
+		# while #566295 is open we really want nbd's c_n to have a DEVICE
+		# when it's closed this just saves some re-running of ipconfig and helps loop
+		# this is caused by nbd being a run-script unlike this script and nfs
+		# we want to export DEVICE (after c_n) so nbd only cares if BOOTIF appears
+
+		# a failed c_n should be slow so don't repeat too many times
+		# do repeat though with sleep, could fail quickly before any device appears
+		FLL_NET_OK=2
+		while [ "${FLL_NET_OK}" -gt 0 ] ; do
+			configure_networking
+			if [ -n "${DEVICE}" ] && [ -e /tmp/net-${DEVICE}.conf ] ; then
+				# DEVICE will be set by c_n unless it was blank
+				#   and no interfaces came up
+				echo "configured networking for ${DEVICE}"
+				FLL_NET_OK=-1
+			else
+				FLL_NET_OK=$((FLL_NET_OK - 1))
+				echo "waiting 5 seconds before retrying networking"
+				sleep 5
+			fi
+		done
+		if [ ${FLL_NET_OK} -eq 0 ] ; then
+			# we still haven't got a good network
+			# either the user specified a device which won't work
+			# or no devices came up
+			panic "${R}Failed to configure networking to prepare for nbdroot${N}"
+		fi
+		# we should have the actual DEVICE that's up now, so export it
+		# nbd will parse IP itself from cmdline
+		# c_n from nbd will have to recognise DEVICE (or BOOTIF or dev from ip)
+		export DEVICE
+		# ROOTPATH will set nbdroot if nbdroot=dhcp
+		# I think c_n should (re)source /tmp/net-%{DEVICE}.conf even if it's already there
+		# as it stands it bombs out before it gets to sourcing the .conf and setting ROOTPATH
+		export ROOTPATH
+		[ "$quiet" != "y" ] && log_end_msg
+	fi
 
 	#
 	# Run scripts in local-top, like lvm2
@@ -591,6 +726,15 @@ mountroot()
 					;;
 				/dev/mapper/*)
 					lvm vgchange -aly --ignorelockingfailure
+					FLL_BLOCKDEVS="${FLL_FROMHD_DEV}"
+					;;
+				/dev/nbd*)
+					# retry nbd if not running
+					# nbd not safe to re-call without test
+					# can hang if FLL_FROMHD_DEV is not from nbdroot
+					# strip partition, only care if rootdev is alive
+					FLL_NBD_DEV=${FLL_FROMHD_DEV#/dev/}
+					/sbin/nbd-client -c ${FLL_NBD_DEV%p*} > /dev/null || /scripts/local-top/nbd
 					FLL_BLOCKDEVS="${FLL_FROMHD_DEV}"
 					;;
 				*)
